config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :services
  resources :activities_tables
  resources :activities
  devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "services#index"
  get '/orders', to: 'orders#index', as: 'orders_index'
  post '/createorder', to: 'orders#create'
  get '/receipts/:id', to: 'receipts#show', as: 'receipt'
  get 'my_orders', to: 'orders#my_orders'
  get 'my_receipts', to: 'receipts#my_receipts'
  get '/Admin', to: 'receipts#admin', as: 'admin'
  patch '/receipts/:id', to: 'receipts#confirm', as: 'update_order'

end

app/controllers/activities_tables_controller.rb
class ActivitiesTablesController < ApplicationController
  before_action :set_activities_table, only: %i[ show edit update destroy ]

  # GET /activities_tables or /activities_tables.json
  def index
    @activities_tables = ActivitiesTable.all
  end

  # GET /activities_tables/1 or /activities_tables/1.json
  def show
  end

  # GET /activities_tables/new
  def new
    @activities_table = ActivitiesTable.new
  end

  # GET /activities_tables/1/edit
  def edit
  end

  # POST /activities_tables or /activities_tables.json
  def create
    @activities_table = ActivitiesTable.new(activities_table_params)

    respond_to do |format|
      if @activities_table.save
        format.html { redirect_to activities_table_url(@activities_table), notice: "Activities table was successfully created." }
        format.json { render :show, status: :created, location: @activities_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activities_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities_tables/1 or /activities_tables/1.json
  def update
    respond_to do |format|
      if @activities_table.update(activities_table_params)
        format.html { redirect_to activities_table_url(@activities_table), notice: "Activities table was successfully updated." }
        format.json { render :show, status: :ok, location: @activities_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activities_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities_tables/1 or /activities_tables/1.json
  def destroy
    @activities_table.destroy

    respond_to do |format|
      format.html { redirect_to activities_tables_url, notice: "Activities table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activities_table
      @activities_table = ActivitiesTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activities_table_params
      params.require(:activities_table).permit(:ordered, :complete)
    end
end

app/helpers/activities_tables_helper.rb
module ActivitiesTablesHelper
end

app/views/activities_tables/_activities_table.html.erb
<div id="<%= dom_id activities_table %>">
  <p>
    <strong>Ordered:</strong>
    <%= activities_table.ordered %>
  </p>

  <p>
    <strong>Complete:</strong>
    <%= activities_table.complete %>
  </p>

</div>

app/views/activities_tables/_form.html.erb
<%= form_with(model: activities_table) do |form| %>
  <% if activities_table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activities_table.errors.count, "error") %> prohibited this activities_table from being saved:</h2>

      <ul>
        <% activities_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ordered, style: "display: block" %>
    <%= form.datetime_field :ordered %>
  </div>

  <div>
    <%= form.label :complete, style: "display: block" %>
    <%= form.check_box :complete %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities_tables/edit.html.erb
<h1>Editing activities table</h1>

<%= render "form", activities_table: @activities_table %>

<br>

<div>
  <%= link_to "Show this activities table", @activities_table %> |
  <%= link_to "Back to activities tables", activities_tables_path %>
</div>

app/views/activities_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activities tables</h1>

<div id="activities_tables">
  <% @activities_tables.each do |activities_table| %>
    <%= render activities_table %>
    <p>
      <%= link_to "Show this activities table", activities_table %>
    </p>
  <% end %>
</div>

<%= link_to "New activities table", new_activities_table_path %>

app/views/activities_tables/new.html.erb
<h1>New activities table</h1>

<%= render "form", activities_table: @activities_table %>

<br>

<div>
  <%= link_to "Back to activities tables", activities_tables_path %>
</div>

app/views/activities_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activities_table %>

<div>
  <%= link_to "Edit this activities table", edit_activities_table_path(@activities_table) %> |
  <%= link_to "Back to activities tables", activities_tables_path %>

  <%= button_to "Destroy this activities table", @activities_table, method: :delete %>
</div>