config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :services
  resources :activities_tables
  resources :activities
  devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "services#index"
  get '/orders', to: 'orders#index', as: 'orders_index'
  post '/createorder', to: 'orders#create'
  get '/receipts/:id', to: 'receipts#show', as: 'receipt'
  get 'my_orders', to: 'orders#my_orders'
  get 'my_receipts', to: 'receipts#my_receipts'
  get '/Admin', to: 'receipts#admin', as: 'admin'
  patch '/receipts/:id', to: 'receipts#confirm', as: 'update_order'

end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def my_receipts
    @receipts = current_user.receipts
  end

  def admin
    @receipts = Receipt.all
  end

  def show
    if(current_user.admin)
      @receipt = Receipt.find(params[:id])
    else
      @receipt = current_user.receipts.find(params[:id])
    end
    @orders = Order.where(receipt_id: @receipt.id)
  end
  
  def confirm
    @receipt = Receipt.find(params[:id])
    @receipt.update_attribute(:paid, true)
    redirect_to admin_path
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/admin.html.erb
<h1>All Receipts</h1>

<style>
table, th, td {
  border: 2px solid black;
  border-collapse: collapse;
}
</style>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created By</th>
      <th>Actions</th>
      <th> Completed services </th>
    </tr>
  </thead>
  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.id %></td>
        <td><%= receipt.user.email %></td>
        <td><%= receipt.created_at %></td>
        <td><%= link_to "View Receipt", receipt_path(receipt) %></td>
        <td> <%= receipt.paid %> </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/receipts/my_receipts.html.erb
<h1>My Receipts</h1>

<style>
table, th, td {
  border: 2px solid black;
  border-collapse: collapse;
}
</style>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.id %></td>
        <td><%= receipt.created_at %></td>
        <td>
          <%= link_to 'Show', receipt_path(receipt) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/receipts/show.html.erb
<table class="body-wrap">
    <tbody><tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tbody><tr>
                        <td class="content-wrap aligncenter">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                <tbody><tr>
                                    <td class="content-block">
                                        <h2>Thanks for staying at our Hotel</h2>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <table class="invoice">
                                            <tbody><tr>
                                                <td><%= @receipt.user.email%><br><%= @receipt.created_at %></td>
                                            </tr>
                                             <% @orders.each do |o| %>
                                            <tr>
                                                <td>
                                                    <table class="invoice-items" cellpadding="0" cellspacing="0">
                                                        <tbody><tr>
                                                            <td><%= o.service.name %></td>
                                                            <td class="alignright"><%= o.priceAtPurchase %>€</td>
                                                        </tr>
                                                    </tbody></table>
                                                </td>
                                            </tr>
                                            <% end %>
                                          </tbody></table>
                                        <% if current_user.admin == true %> 
                                         <tr>
                                            <td class="content-block">
                                                <%= link_to "Confirm", update_order_path(@receipt), data: { "turbo-method": :patch } %>
                                            </td>
                                        </tr>
                                        <% end %>
                                    </td>
                                </tr>
                                <tr>
                            </tbody></table>
                        </td>
                    </tr>
                </tbody></table>
                <div class="footer">
                    <table width="100%">
                        <tbody><tr>
                        </tr>
                    </tbody></table>
                </div></div>
        </td>
        <td></td>
    </tr>
</tbody></table>


    
    
    <br>